name: sakt
description: "Application SAK-T"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.8.0

dependencies:
  carousel_slider: ^5.1.1
  change_app_package_name: ^1.5.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo2.png
